### ISSUE TITLE
please colour greenland

### ISSUE THREAD

**Issue by dieterdreist** [Gustavo22Soaresh/osm-comunity-survey#2]
Denmark has respondents so greenland should be coloured in the countries map ;-)

**Comment by Gustavo22Soaresh** [comment]
Although Greenland is part of the Kingdom of Denmark, it has had significant autonomy since 1979 and is officially recognized as an "autonomous community" within the kingdom. For example, Greenland has its own government, controls its internal policies, and is not part of the European Union, unlike Denmark.

In research, it is common for territories with significant autonomy to be treated separately to reflect their social, political, and cultural particularities. This approach is not a disregard for the historical and political connection to Denmark but rather a methodological choice to better capture regional nuances.
